import { createSlice } from "@reduxjs/toolkit";

/**
 * Type representing the state of the counter
 */
export type CounterState = {
  data: number; // Current counter value
};

/**
 * Initial state for the counter slice
 */
const initialState: CounterState = {
  data: 42, // Default starting value
};

/**
 * Redux Toolkit slice for counter functionality
 * Includes reducers for incrementing and decrementing
 */
export const counterSlice = createSlice({
  name: "counter",
  initialState,
  reducers: {
    /**
     * Increment the counter by the given payload value
     */
    increment: (state, action) => {
      state.data += action.payload;
    },
    /**
     * Decrement the counter by the given payload value
     */
    decrement: (state, action) => {
      state.data -= action.payload;
    },
  },
});

// Export actions generated by createSlice
export const { increment, decrement } = counterSlice.actions;

/**
 * Legacy action creator for incrementing (pre-Redux Toolkit)
 * @param amount Amount to increment (default 1)
 */
export function incrementLegacy(amount = 1) {
  return {
    type: "increment",
    payload: amount,
  };
}

/**
 * Legacy action creator for decrementing (pre-Redux Toolkit)
 * @param amount Amount to decrement (default 1)
 */
export function decrementLegacy(amount = 1) {
  return {
    type: "decrement",
    payload: amount,
  };
}

/**
 * Legacy reducer function for counter (pre-Redux Toolkit)
 * Handles increment and decrement actions
 */
export default function counterReducer(
  state = initialState,
  action: { type: string; payload: number }
) {
  switch (action.type) {
    case "increment":
      return {
        ...state,
        data: state.data + action.payload,
      };
    case "decrement":
      return {
        ...state,
        data: state.data - action.payload,
      };
    default:
      return state;
  }
}
